const VIEWPORT_WIDTH_RESIZING_TIMEOUT = 1000;
const INFO_POPUP_TIMEOUT = 8000;

const MAIN_API_BASE_URL = 'http://localhost:4000'; //'https://api.beatfilms.greysmouse.nomoredomains.monster';
const MOVIES_API_BASE_URL = 'https://api.nomoreparties.co';

const USER_NAME_REGEXP = /^[A-Za-zА-Яа-я -]*$/;

const SHORT_MOVIE_DURATION_LIMIT = 40;

const SCREEN_WIDTH_CHECKPOINT_768PX = 768;
const SCREEN_WIDTH_CHECKPOINT_425PX = 425;

const MOVIES_CARD_MIN_COUNT_DEFAULT = 12;
const MOVIES_CARD_MIN_COUNT_768PX = 8;
const MOVIES_CARD_MIN_COUNT_425PX = 5;

const MOVIES_CARD_UPLOAD_COUNT_DEFAULT = 3;
const MOVIES_CARD_UPLOAD_COUNT_768PX = 2;
const MOVIES_CARD_UPLOAD_COUNT_425PX = 2;

export {
  VIEWPORT_WIDTH_RESIZING_TIMEOUT,
  INFO_POPUP_TIMEOUT,
  MAIN_API_BASE_URL,
  MOVIES_API_BASE_URL,
  USER_NAME_REGEXP,
  SHORT_MOVIE_DURATION_LIMIT,
  SCREEN_WIDTH_CHECKPOINT_768PX,
  SCREEN_WIDTH_CHECKPOINT_425PX,
  MOVIES_CARD_MIN_COUNT_DEFAULT,
  MOVIES_CARD_MIN_COUNT_768PX,
  MOVIES_CARD_MIN_COUNT_425PX,
  MOVIES_CARD_UPLOAD_COUNT_DEFAULT,
  MOVIES_CARD_UPLOAD_COUNT_768PX,
  MOVIES_CARD_UPLOAD_COUNT_425PX
};
